title: AWS DEA Guia de Estudos
description: Material de estudos para a certificação AWS Certified Data Engineer - Associate
lang: pt-BR
repository_url: https://github.com/Ito-Santana/aws-dea-guia-estudos

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
